services:
  postgres:
    image: bitnami/postgresql
    container_name: api-solid-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apisolid
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata:
